[package]
name = "chinadns-rust"
version = "0.1.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]

[dependencies]
trust-dns-proto = { git = "https://github.com/bluejekyll/trust-dns" }
trust-dns-server = { git = "https://github.com/bluejekyll/trust-dns" }
trust-dns = { git = "https://github.com/bluejekyll/trust-dns", default-features = false, features = ["dns-over-rustls"] }
tokio = "0.1.11"
slog = "2.4.1"
sloggers = "0.3.1"
lazy_static = "1.1.0"
parking_lot = { version = "0.6.4", features = ["nightly"] }
lock_api = "0.1.4"

[patch."https://github.com/bluejekyll/trust-dns"]
trust-dns-proto = { git = "https://github.com/sticnarf/trust-dns", branch = "generalize-rrset-records" }
trust-dns-server = { git = "https://github.com/sticnarf/trust-dns", branch = "generalize-rrset-records" }
trust-dns = { git = "https://github.com/sticnarf/trust-dns", branch = "generalize-rrset-records", default-features = false, features = ["dns-over-rustls"] }

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'