[package]
name = "chinadns-rust"
version = "0.1.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]

[dependencies]
trust-dns-proto = "0.5.0-alpha.5"
trust-dns-server = "0.15.0-alpha.2"
trust-dns = { version = "0.15.0-alpha.2", default-features = false, features = ["dns-over-rustls"] }
tokio = "0.1.11"
slog = "2.4.1"
sloggers = "0.3.1"
lazy_static = "1.1.0"