bind = "127.0.0.1:5300"

[upstreams]
  [upstreams.dnspod]
  address = "119.29.29.29"
  network = "udp"

  [upstreams.alidns]
  address = "223.5.5.5"
  network = "udp"

  [upstreams.opendns]
  address = "208.67.222.222:5353"
  network = "tcp"

  [upstreams.cloudflare]
  address = "1.1.1.1"
  network = "tls"
  tls-host = "cloudflare-dns.com"

[ranges]
  [ranges.cn]
  files = ["chnroutes.txt"]

[[rules]]
upstreams = ["dnspod", "alidns"]
ranges = ["!cn"]
action = "drop"