bind = "127.0.0.1:5300"

[upstreams]
  [upstreams.google]
    address = "8.8.8.8"
    network = "udp"

  [upstreams.opennic]
  address = "185.121.177.177"
  network = "udp"
  default = false

[domains]
  [domains.opennic]
  list = [
    ".bbs", ".chan", ".cyb", ".dyn", ".geek", ".gopher", ".indy",
    ".libre", ".neo", ".null", ".o", ".oss", ".oz", ".parody", ".pirate"
  ]

[[requests]]
domains = ["opennic"]
upstreams = ["opennic"]